apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: ip-check
  name: ip-check
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: ip-check
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ./docker-compose.yml convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: ip-check
    spec:
      containers:
        - image: fatmatto/ip-check
          imagePullPolicy: "IfNotPresent"
          name: ip-check
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
